### ISSUE TITLE
Mejorar el manejo de error del backend

### ISSUE THREAD

**Issue by fdodino** [ItuFede/Lost-Paws-documentation#4]
En `updateLostPetStatus.js`

```js
const main = async (event, context) => {
  try {

    const body = JSON.parse(event.body)
    const id = body.id

    const position = {
      Latitud: body.Latitud, //body.latitude,
      Longitud: body.Longitud //body.longitude
    }

    // polémico: falta devolver un 400: Bad request
    if (!id || !position.Latitud || !position.Longitud) return
```

1. debe devolver un 400 por cada tipo de error posible
2. podría haber objetos de dominio pero bueno... por ahora no molesta tanto
3. revisar con CDK qué error tira si la API Key es inválida, tiene que ser estándar respecto al formato de dónde se manda el mensaje de error

**Comment by fdodino** [comment]
Falta

- trabajar cada error (falta id, falta latitud, falta longitud)
- recolectar toda la lista de errores y enviar un mensaje junto con el bad request (hoy está dejando el mensaje vacío)

**Comment by ItuFede** [comment]
Done
