### ISSUE TITLE
[Backend] Usar el interceptor httpErrorWrapper

### ISSUE THREAD

**Issue by fdodino** [ItuFede/Lost-Paws-documentation#5]
Esto implica que los endpoints ya no necesitan tener un try/catch.

Cosas que pueden pasar por el wrapper

- todo ok, 200 y en el body lo que te llega de cada endpoint
- no tenés token => 401
- tenés token pero expiró, o las credenciales son inválidas => técnicamente es más un 401
- tenés credenciales bien pero no tenés permisos => 403
- la excepción es un UserError o de alguna manera lo podés saber => 400
- caso contrario => default a 500

**Comment by ItuFede** [comment]
Done
